flowchart LR
  subgraph Collections
    CUSR[[UsersCollection]]
    CAST[[AssetsCollection]]
    CEL[[ElementsCollection]]
    CCOMP[[ComponentsCollection]]
    CCA[[CreativeAssemblyCollection]]
    CCD[[CreativeDynamicCollection]]
    CCI[[CreativeInteractiveCollection]]
  end

  subgraph Views
    VUNI[[CreativeUnifiedView]]
    VUNIEL[[CreativeUnifiedViewElements]]
    VCA[[CreativeAssemblyView]]
    VCD[[CreativeDynamicView]]
    VCI[[CreativeInteractiveView]]
    VEA[[ElementsAssetsView]]
    VEB[[ElementsBindingView]]
  end

